export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
        <head>
          <title>My first page with next js</title>
        </head>
      <body>{children}</body>
    </html>
  )
}
